### ISSUE TITLE
Crash (w/ data loss) on "Message is too long" error 

### ISSUE THREAD

**Issue by neooleg** [rahiel/telegram-send#12]
## Bug
It's hard to say (sorry, can't see it again) how big message was to reproduce the issue, but I'm sure if to send a big amount of text (e.g. wiki page) it will rise the error like this:

> Traceback (most recent call last):   File "/usr/local/bin/telegram-send", line 11, in <module>     sys.exit(main())   File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 70, in main     send(messages=args.message, conf=args.conf, parse_mode=args.parse_mode, files=args.file, images=args.image, captions=args.caption)   File "/usr/local/lib/python3.4/dist-packages/telegram_send.py", line 112, in send     bot.send_message(chat_id=chat_id, text=m, parse_mode=parse_mode)   File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 125, in decorator     result = func(self, *args, **kwargs)   File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 158, in decorator     return Bot._message_wrapper(self, url, data, *args, **kwargs)   File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 146, in _message_wrapper     result = self._request.post(url, data, timeout=kwargs.get('timeout'))   File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 246, in post     **urlopen_kwargs)   File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 188, in _request_wrapper     raise BadRequest(message) telegram.error.BadRequest: Message is too long

### Idea
- Divide messages on smaller one to send a couple of them

### Quick
- Send a first message only
- Rise warning, but not an error leading to crash with **data loss because no any messages to send**

**Comment by rahiel** [comment]
On data loss: I recommend saving data to a file before sending if it's important, because you could also have other errors like Telegram connection problems.

The max message length is currently 4096 characters, and is enforced by Telegram's servers. I released a new version that splits up larger messages into smaller ones.

**Comment by neooleg** [comment]
> I released
@rahiel did you _already_ released?

**Comment by rahiel** [comment]
@neooleg yes, the splitting is available in version 0.9.2, which is currently on pypi.

**Comment by neooleg** [comment]
OK, I updated the app. Will try.

**Comment by rahiel** [comment]
I'm assuming this issue was fixed, feel free to reopen if it wasn't.
