### ISSUE TITLE
No module named 'telegram-send', installed from AUR

### ISSUE THREAD

**Issue by Goosegit11** [rahiel/telegram-send#125]
```
Traceback (most recent call last):
  File "/sbin/telegram-send", line 5, in <module>
    from telegram_send.telegram_send import main
ModuleNotFoundError: No module named 'telegram_send'

```

**Comment by rahiel** [comment]
Please install the latest version using pip as documented in the README. The AUR package should be updated as the previous version is broken.

**Comment by Goosegit11** [comment]
Oh I fixed it a long time ago, by choosing older version or something. Thanks.
