### ISSUE TITLE
Traceback issue when run

### ISSUE THREAD

**Issue by AlexKLMan** [rahiel/telegram-send#126]
Hi there, I haven't used this program for over a year, but it was working on my Raspberry Pi 4 a year ago.
When I try to run the .conf files with telegram-send NAME.conf I get the following error:

Traceback (most recent call last):                                                                                      
  File "/home/alex/.local/bin/telegram-send", line 5, in <module>                                                       
    from telegram_send.telegram_send import main                                                                        
  File "/home/alex/.local/lib/python3.9/site-packages/telegram_send/__init__.py", line 2, in <module>                   
    from .telegram_send import configure, send                                                                          
  File "/home/alex/.local/lib/python3.9/site-packages/telegram_send/telegram_send.py", line 33, in <module>             
    from telegram.constants import MAX_MESSAGE_LENGTH                                                                   
ImportError: cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram.constants' (/home/alex/.local/lib/python3.9/site-packages/telegram/constants.py)                                                                                            

I'm not sure if I missed a step during installation as I haven't used this for some time now. I believe it's to do with  version compatibility?

Has anyone found a fix or is this being updated elsewhere?
Thank you!

**Comment by shenberg** [comment]
To solve this, I ran `pip install python-telegram-bot==13.11`

I had the same issue, it's because for some reason the `python-telegram-bot` dependency gets the latest version installed, instead of version that `telegram-send` expects, which is `13.11`, taken from `Pipfile.lock`

**Comment by rahiel** [comment]
This bug is fixed in the latest release, please upgrade `pip install --upgrade telegram-send`
