### ISSUE TITLE
How to use telegram-send by proxy

### ISSUE THREAD

**Issue by tusik** [rahiel/telegram-send#13]
I want use telegram-send in python, but i can only connect tekegram server by proxy.
How to use telegram-send with proxy in python, i don't want set proxy globa.
Could you help me?

**Comment by rahiel** [comment]
You can set a proxy with an environment variable, for example:
```
https_proxy=https://ip:port telegram-send "hello"
```

Within Python you can set the environment variable with:
```
os.environ["https_proxy"] = "https://ip:port"

**Comment by rahiel** [comment]
@tusik It should be `telegram_send.send(["hello"])`, it takes a list of strings as messages.

**Comment by tusik** [comment]
@rahiel Thank you, it's very helpful to me
