### ISSUE TITLE
Send an image from Python

### ISSUE THREAD

**Issue by apacha** [rahiel/telegram-send#14]
I am trying to send an image with telegram-send. The message sending works fine, but I can't find any details in the documentation about how to send images. The signature indicates that it is expecting a `file`, whatever that means.

```python
import telegram_send
telegram_send.send(["message"], images=[what_to_put_here])
```

I've tried with the following options, but none of these work:
```python
import base64
from PIL import Image

# Open image with Pillow
image = Image.open('2017-06-22_vgg4_99.9p.png')
telegram_send.send(["message"], images=[image])

# Serialize into bytes
imageBytes = image.tobytes()
telegram_send.send(["message"], images=[imageBytes])

# Encode with base64
imageBase64 = base64.encodebytes(imageBytes)
telegram_send.send(["message"], images=[imageBase64])

# Just open a file and try that
f = open('2017-06-21_vgg_staff74_192x96_Adadelta.txt')
telegram_send.send(["message"], images=[f])
```

I am getting either `telegram.error.BadRequest: Wrong persistent file_id specified: wrong string length` or something like `TypeError: <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=800x600 at 0x19D5281EE48> is not JSON serializable`. 

I actually found the answer here: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#post-an-image-from-memory

Now my code looks like this:
```python
from PIL import Image
from io import BytesIO

image_path = 'MyFile.png'
byteStream = BytesIO()
byteStream.name = image_path
image = Image.open(image_path)
image.save(byteStream, "png")
byteStream.seek(0)
telegram_send.send([message], parse_mode="Markdown", images=[byteStream])
```

I believe this deserves at least a place in the documentation. Actually it would be even better, if the `telegram_send.send()`-method would accept `Pillow`-images and do this conversion into a byte-stream internally.

**Comment by rahiel** [comment]
> The signature indicates that it is expecting a file, whatever that means.

This refers to a [file object](https://docs.python.org/3/glossary.html#term-file-object). You need to open images/files in binary more, or else Python will try to decode the file into text. So:
``` python
import telegram_send

with open("image.jpg", "rb") as f:
    telegram_send.send(images=[f])
```

**Comment by rahiel** [comment]
I've added how to send images/files to the [docs](https://pythonhosted.org/telegram-send/api/).

**Comment by apacha** [comment]
Oh. that explains a lot. Thanks for adding it to the docs.
