### ISSUE TITLE
Newline \n possibility

### ISSUE THREAD

**Issue by smoneck** [rahiel/telegram-send#15]
Hey!

Could you tell me whether there is a way to go to the next line when sending messages?

Like e.g.:

```
telegram-send --format html "Line1<br />Line2"
telegram-send "Line1\nLine2"
...
```

That would be really handy for messages in the shape of

> error on `systemname`
> time `time`
> Content: `log`

Thank you very much for all the work!

**Comment by smoneck** [comment]
I noticed accidentally that it works when I call it from `python` using:

    import subprocess
    subprocess.call(["/usr/local/bin/telegram-send", "test\ntest"])

**Comment by rahiel** [comment]
You can type a message like this `telegram-send "line1` and then press enter to continue to the next line. But this is cumbersome, so I released a new version with the `--stdin` flag, so you pipe output to telegram-send:
``` shell
printf "error on debian\ntime 1501255976\nContent: new version of telegram-send, please upgrade!" | telegram-send --stdin
```

**Comment by smoneck** [comment]
Awesome, thanks! :-)
