### ISSUE TITLE
Send to private channel

### ISSUE THREAD

**Issue by CrCs2O4** [rahiel/telegram-send#16]
Hey! First of all, thanks for great project.

When I was trying to configure/send message to private channel I saw an error `telegram.error.BadRequest: Chat not found`.

Following [this comment](https://github.com/python-telegram-bot/python-telegram-bot/issues/538#issuecomment-287231847) at `python-telegram-bot` repo I finished with workaround - manual changing `example.conf` file with `chat_id=-100NUMBER`.

Now `telegram-send --config example.conf 'hello world'` works with private channels.

Want to share this for everybody who needs this functionality. I can create PR for adding this workaround to `README.md` if you want. But if you add this as step `--configure-channel` stage it'll be much better.

Thanks!

**Comment by rahiel** [comment]
Thanks for notifying me!

I'll look at adding support for private channels to the `--configure-channel` option.

**Comment by rahiel** [comment]
Version 0.12 now supports configuring private channels.

**Comment by ixzh** [comment]
this is not working anymore? now the telegram web z url looks like: `https://web.telegram.org/z/#-NUMBER`

**Comment by UmarbekSaidov** [comment]
Channel tuning didn't work for me either
![photo_2023-08-28_15-31-19](https://github.com/rahiel/telegram-send/assets/96768102/6b66b4e7-2f2e-4e58-8a06-5566a2072173)
