### ISSUE TITLE
Suggestion for sending image files

### ISSUE THREAD

**Issue by Qwerty-Space** [rahiel/telegram-send#17]
Hello,

I would love to be able to send an image file uncompressed, then the compressed version immediately after with one command.

**Comment by JuanPotato** [comment]
I mean, you can do `telegram-send -f bitmap.png -i bitmap.png`

**Comment by Qwerty-Space** [comment]
Oh, didn't know that.
I tried `telegram-send -fi bitmap.png`

**Comment by rahiel** [comment]
As @JuanPotato mentioned, you can do: `telegram-send -f bitmap.png -i bitmap.png`

You can also always do it with two invocations: 
`telegram-send -i image.png && telegram-send -f image.png` if you want to control the order.

**Comment by Qwerty-Space** [comment]
The thing is, I have a channel where I send loads of pictures, and their compressed forms first.  I was hoping this would make it easier.
