### ISSUE TITLE
Errors whilst trying to send a file/image

### ISSUE THREAD

**Issue by Qwerty-Space** [rahiel/telegram-send#18]
As an image
https://pastebin.com/N2XnkZum

As a file
https://pastebin.com/yJCpND7c

**Comment by Qwerty-Space** [comment]
https://github.com/rahiel/telegram-send/pull/19

**Comment by rahiel** [comment]
@Qwerty-Space I've released a new version with a longer default timeout, could you check if that solves the problem?
