### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by fabbrus97** [rahiel/telegram-send#23]
Hello, I've tried to install telegram-send on Ubuntu 17.04 without sudo, but this is what I get when I do `pip3 install telegram_send.py`:
`Collecting telegram_send.py `
`  Could not find a version that satisfies the requirement telegram_send.py (from versions: )
No matching distribution found for telegram_send.py
`
What can I do?

**Comment by rahiel** [comment]
The correct command is `pip3 install telegram-send`, see the [installation instructions](https://github.com/rahiel/telegram-send#install). You'll have to modify your path, see the linked guide there.

**Comment by fabbrus97** [comment]
It works, sorry for my inattention... great work!
