### ISSUE TITLE
telegram-send in bash script

### ISSUE THREAD

**Issue by elanozturk** [rahiel/telegram-send#24]
When i try to use "telegram-send" in bash script like that:

```
#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

telegram-send --image image.jpg
```
i get this error : 
```
Config not found
Please run: telegram-send --configure
```
it's already configured.

**Comment by rahiel** [comment]
Are you running the script as the same user you've configured `telegram-send` with?

**Comment by elanozturk** [comment]
Yes it's. I've configured both user and root.Now i changed the path to  `/home/me/.local/share/nautilus/scripts` but no luck. I want to use it with cron.

**Comment by rahiel** [comment]
Have you seen the [cron example](https://github.com/rahiel/telegram-send#periodic-messages-with-cron)? In this case explicitly passing the config location at configure/sending would help.

**Comment by elanozturk** [comment]
I will give a try.I found my `telegram-send.conf` file and putted in` /.local/bin/` where the telegram-send file,but doesn't work.

**Comment by rahiel** [comment]
Explicitly passing `--config ~/some/path/telegram-send.conf` with `--configure` and subsequently with any sending command you like, should work.

You could also use the new option `--global-config` or `-gc` to use the configuration file at `/etc/telegram-send.conf`. So you do `sudo telegram-send -gc --configure` and then `telegram-send -gc --image image.jpg` in your cronjob. Add `--upgrade` to the `pip3` command you used to upgrade telegram-send.

**Comment by elanozturk** [comment]
Thank you now it's work with `--config ~/some/path/file.conf`.

**Comment by LUCASdario150** [comment]
is possible that he used python 2.7,therefore not run. 
I updated to python3 and run perfect.
