### ISSUE TITLE
Include caption with name of file

### ISSUE THREAD

**Issue by leninberg** [rahiel/telegram-send#26]
Hi again!
I tried to send several files at once and it worked.
Now I would like to include a caption with every file, the caption should be the complete filename
Reason for this is sometimes I have very long filenames and I can't see them on telegram (it cuts the filenames when they are long)
so how could I do it when I execute
`telegram-send --file /path/to/files/*.txt`
for every of those text files to be sent with a caption of their filenames?
Thanks again!

**Comment by rahiel** [comment]
Hi,

I haven't implemented captions for files yet, so this is not possible yet.
For now you could send the filename as separate message:
``` shell
telegram-send filename.pdf --file filename.pdf
```
That doesn't work well with multiple files, for that use a for loop:
``` bash
for f in /path/to/files/*.txt; do
    telegram-send "$f" && telegram-send --file "$f"
done

```

**Comment by leninberg** [comment]
Hi!
Thanks for all the help!
I tried what you suggested and it works wonderfully! As long as there are files there in that folder to be sent.
Problem is when the folder is empty, it sends this message to my telegram.
/home/myusername/thefolderspecified/*.txt

Sorry to bother you again.

**Comment by rahiel** [comment]
> However, how can you send just the filename, and not the complete path+filename?

You can get the filename from a path with `basename`:

``` shell
for f in /path/to/files/*.txt; do
    telegram-send $(basename "$f") && telegram-send --file "$f"
done
```

Maybe it'd help to learn some Bash scripting, I've learned from this guide: http://mywiki.wooledge.org/BashGuide.

**Comment by rahiel** [comment]
This was implemented in https://github.com/rahiel/telegram-send/commit/1aa5d6db7674d728799b40d4c0e785e0970832a9, it will be available in the next release.
