### ISSUE TITLE
Please add the option "disable_web_page_preview=True"

### ISSUE THREAD

**Issue by auroracoin-tools** [rahiel/telegram-send#28]
Please add the option "disable_web_page_preview=True" to be able to send links without preview. this is a crucial feature for me.

**Comment by rahiel** [comment]
This was implemented in fd80103084bf35a192ab9a20538c89f59985932a and released in version 0.19, please upgrade (`pip3 install --upgrade telegram-send`).

Example:
```shell
telegram-send --disable-web-page-preview "https://github.com/rahiel/telegram-send"
```

**Comment by auroracoin-tools** [comment]
How do I call this in the php function? (my line now is like this: telegram_send.send(messages=[alert], conf='~/channel.conf')

**Comment by auroracoin-tools** [comment]
got it, thanks. (example below)

telegram_send.send(messages=[alert], disable-web-page-preview='true' ,conf='~/channel.conf')

**Comment by rahiel** [comment]
> got it, thanks. (example below)
> 
> telegram_send.send(messages=[alert], disable-web-page-preview='true' ,conf='~/channel.conf')

That doesn't look right, it should be:
``` python
telegram_send.send(messages=[alert], disable_web_page_preview=True , conf='~/channel.conf')
```
Note the difference between `disable-web-page-preview` and `disable_web_page_preview`

**Comment by auroracoin-tools** [comment]
That´s correct, sorry about that.. but in my case, I must put the "True" into single quotes to get it to work.

telegram_send.send(messages=[alert], disable_web_page_preview='True' , conf='~/channel.conf')

i am using php 2.7.12 if that matters.
