### ISSUE TITLE
Send images/files from URLs

### ISSUE THREAD

**Issue by waristh** [rahiel/telegram-send#29]
How can i send picture/images from URL.

**Comment by rahiel** [comment]
That's currently not supported. I'll add that in a new version when I find some time.

**Comment by bamtan** [comment]
You can do this by sending a message with markdown formatting, e.g. `telegram-send --format markdown "[​​​​](IMAGE_URL)"`

**Comment by rahiel** [comment]
You can get an image preview in the telegram app using for example:
```
telegram-send 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/320px-Test-Logo.svg.png'
```

Otherwise this should be done using some custom script.
