### ISSUE TITLE
Configure-Channel Broken

### ISSUE THREAD

**Issue by joesixpack** [rahiel/telegram-send#32]
Occurs after pasting in the priv channel URL:

![image](https://user-images.githubusercontent.com/23145642/39096940-8d65eeca-460a-11e8-9180-f68638a03326.png)

**Comment by rahiel** [comment]
I can't reproduce this with a newly made private channel. You have to paste the URL in your address bar when viewing your channel in the web.telegram.org client, so the URL that starts with "https://web.telegram.org", not the one that starts with "https://t.me".

If you did paste the right URL, please share it here.

**Comment by rahiel** [comment]
Closing because I can't reproduce this and this bug report is incomplete: I need the channel URL to look at this. Feel free to re-open if you have more information on this issue.

**Comment by ixzh** [comment]
I can confirm this is not working for my private channel.
