### ISSUE TITLE
how can i send message to another room?

### ISSUE THREAD

**Issue by adamzchmbr** [rahiel/telegram-send#35]
i want to send different messages to different rooms.
do i have to change configure each time?
or does another command exist?

thankyou

**Comment by rahiel** [comment]
You can specify your config file for specific groups (you can use the configure command you need):
``` shell
telegram-send --config group1.conf --configure-group
telegram-send --config group2.conf --configure-group
```

And then send to different groups by choosing them:
``` shell
telegram-send --config group1.conf "hello!"
```

Or to the other group:
``` shell
telegram-send --config group2.conf "hello!"
```

With the `group1.conf` you set the location of the config file. So you also choose the group with the `--config groupX.conf` option.

**Comment by adamzchmbr** [comment]
you save me! thankyou!
