### ISSUE TITLE
how can i send many photos at once (framed format)?

### ISSUE THREAD

**Issue by adamzchmbr** [rahiel/telegram-send#36]
i send only one image from raspbian to channel and it success.
but many images case, just run the send_photo command several times.
but other one send many images in a framed format.

how can i do that?
https://imgur.com/a/JBzgtcx

**Comment by rahiel** [comment]
You can send multiple images with one command:
``` shell
telegram-send --image photo1.jpg photo2.jpg photo3.jpg
```
You can send as many images with one command as you want.

I don't know how to send multiple images in a frame.

**Comment by adamzchmbr** [comment]
@rahiel 
it seems to be possible only in the mobile application.

**Comment by rahiel** [comment]
Looks like you can't send them framed with the [Bot API](https://core.telegram.org/bots/api); closing.

**Comment by xoff1337** [comment]
https://core.telegram.org/bots/api#sendmediagroup

> Похоже, вы не можете отправить их в рамках [Bot API](https://core.telegram.org/bots/api) ; закрытие.
