### ISSUE TITLE
Will $ torify telegram-send; work properly?

### ISSUE THREAD

**Issue by leftside2** [rahiel/telegram-send#37]
Plz tell me how to use $ https_proxy="https://127.0.0.1:xxxxx" telegram-send "test";.

127.0.0.1:9170 (which is well used with telegram desktop tcp proxy settings) spits lots of error msgs.

**Comment by rahiel** [comment]
Thanks for asking. I will look at Tor support when I find the time.

**Comment by leftside2** [comment]
Thanks!

**Comment by rahiel** [comment]
I can't guarantee all networking will actually go through Tor, I suggest to use https://www.qubes-os.org/ or https://tails.boum.org/ (in a VM) and use telegram-send from there.
