### ISSUE TITLE
Any options for mute sending?

### ISSUE THREAD

**Issue by leftside2** [rahiel/telegram-send#38]
For example, $ telegram-send "hello before you get up!" --mute; would not ring a bell on the recipient phone side.

**Comment by rahiel** [comment]
Thanks for your suggestion, I will implement this option in a future release.

**Comment by leftside2** [comment]
Thanks!

**Comment by rahiel** [comment]
Thanks for waiting, I've added a `--silent` option in https://github.com/rahiel/telegram-send/commit/19dcba044ff62c404d10c939b651499844e8abab. This will be available in the next release.
