### ISSUE TITLE
telegram-send requires sudo to run

### ISSUE THREAD

**Issue by jk-1** [rahiel/telegram-send#39]
I installed telegram-send into Ubuntu 16.04 box using the command:

	sudo pip3 install telegram-send
	The directory '/home/jk/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	The directory '/home/jk/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	Collecting telegram-send
	  Downloading https://files.pythonhosted.org/packages/3c/d8/03c1e644fd5e7cb4d12506178fbf27cbfc3f0449c839a41f7cf349b05d6b/telegram_send-0.20-py2.py3-none-any.whl
	Collecting colorama (from telegram-send)
	  Downloading https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
	Collecting python-telegram-bot>=5.0 (from telegram-send)
	  Downloading https://files.pythonhosted.org/packages/f1/51/d1bd383522c12b313eddd7b97b8e7d6cd2a8e3b44b8ff3c88e4a7b045cc8/python_telegram_bot-10.1.0-py2.py3-none-any.whl (298kB)
	    100% |████████████████████████████████| 307kB 1.9MB/s 
	Collecting appdirs (from telegram-send)
	  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
	Collecting certifi (from python-telegram-bot>=5.0->telegram-send)
	  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
	    100% |████████████████████████████████| 153kB 3.3MB/s 
	Collecting future>=0.16.0 (from python-telegram-bot>=5.0->telegram-send)
	  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
	    100% |████████████████████████████████| 829kB 1.3MB/s 
	Installing collected packages: colorama, certifi, future, python-telegram-bot, appdirs, telegram-send
	  Running setup.py install for future ... done
	Successfully installed appdirs-1.4.3 certifi-2018.8.24 colorama-0.3.9 future-0.16.0 python-telegram-bot-10.1.0 telegram-send-0.20
	You are using pip version 8.1.1, however version 18.0 is available.
	You should consider upgrading via the 'pip install --upgrade pip' command.

When I try to run telegram-send I get:

	jk@mypc:~$ telegram-send
	Traceback (most recent call last):
	  File "/usr/local/bin/telegram-send", line 7, in <module>
	    from telegram_send import main
	  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
	  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
	  File "<frozen importlib._bootstrap_external>", line 766, in get_code
	  File "<frozen importlib._bootstrap_external>", line 818, in get_data
	PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/telegram_send.py'

	jk@mypc:~$ ls -al  /usr/local/lib/python3.5/dist-packages/telegram_send.py
	-rw-r----- 1 root staff 17633 elo   28 09:26 /usr/local/lib/python3.5/dist-packages/telegram_send.py

Are these normal permissions after install?

When I run sudo telegram-send, it seems to work:

	jk@mypc:~$ sudo telegram-send
	[sudo] password for jk: 
	Config not found
	Please run: telegram-send --configure

I run 

	sudo chmod 644 /usr/local/lib/python3.5/dist-packages/telegram_send.py

And then try again

	jk@mypc:~$ telegram-send
	Traceback (most recent call last):
	  File "/usr/local/bin/telegram-send", line 7, in <module>
	    from telegram_send import main
	  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 29, in <module>
	    from telegram.constants import MAX_MESSAGE_LENGTH
	ImportError: No module named 'telegram.constants'

So it seems that chmoding /usr/local/lib/python3.5/dist-packages/telegram_send.py does not help.

How to fix this?

**Comment by rahiel** [comment]
This sounds like a problem with an older version of pip3 (from your first output: `You are using pip version 8.1.1, however version 18.0 is available.`). You could install telegram-send for a single user without root permissions as described in the readme, or you could uninstall telegram-send and its dependencies:
``` python
sudo pip3 uninstall appdirs certifi colorama future python-telegram-bot telegram-send
```
And then try again with:
``` python
sudo -H pip3 install telegram-send
```

**Comment by jk-1** [comment]
I uninstalled following packages:

	sudo pip3 uninstall appdirs certifi colorama future python-telegram-bot telegram-send

I managed to get pip updated:

	jk@mypc:~$ sudo pip3 --version
	pip 18.0 from /usr/local/lib/python3.5/dist-packages/pip-18.0-py3.5.egg/pip (python 3.5)


Install went ok:

	sudo -H pip3 install telegram-send
	jk@mypc:~$ sudo -H pip3 install telegram-send
	Collecting telegram-send
	  Downloading https://files.pythonhosted.org/packages/3c/d8/03c1e644fd5e7cb4d12506178fbf27cbfc3f0449c839a41f7cf349b05d6b/telegram_send-0.20-py2.py3-none-any.whl
	Requirement already satisfied: appdirs in /usr/local/lib/python3.5/dist-packages (from telegram-send) (1.4.3)
	Requirement already satisfied: python-telegram-bot>=5.0 in /usr/local/lib/python3.5/dist-packages (from telegram-send) (10.1.0)
	Requirement already satisfied: colorama in /usr/local/lib/python3.5/dist-packages (from telegram-send) (0.3.9)
	Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.5/dist-packages (from python-telegram-bot>=5.0->telegram-send) (0.16.0)
	Requirement already satisfied: certifi in /usr/local/lib/python3.5/dist-packages (from python-telegram-bot>=5.0->telegram-send) (2018.8.24)
	Installing collected packages: telegram-send
	Successfully installed telegram-send-0.20


But it runs only with sudo ...

	jk@mypc:~$  telegram-send  --version
	Traceback (most recent call last):
	  File "/usr/local/bin/telegram-send", line 7, in <module>
	    from telegram_send import main
  	File "<frozen importlib._bootstrap>", line 969, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  	File "<frozen importlib._bootstrap_external>", line 661, in exec_module
	  File "<frozen importlib._bootstrap_external>", line 766, in get_code
	  File "<frozen importlib._bootstrap_external>", line 818, in get_data
	PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/telegram_send.py'
	jk@mypc:~$ 
	jk@mypc:~$ sudo telegram-send  --version
	telegram-send 0.20


Configuration fails every time I hit enter after /newbot. Same output for --configure, --configure-group or --configure-channel

	jk@mypc:~$ sudo telegram-send  --configure
	Talk with the BotFather on Telegram (https://telegram.me/BotFather), create a bot and insert the token
	❯ /newbot
	Something went wrong, please try again.
	
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 254, in configure
	    bot = telegram.Bot(token)
	  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 108, in __init__
    	self.token = self._validate_token(token)
	  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 134, in _validate_token
    	raise InvalidToken()
	telegram.error.InvalidToken: Invalid token
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/local/bin/telegram-send", line 11, in <module>
    	sys.exit(main())
	  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 79, in main
	    return configure(conf, fm_integration=True)
	  File "/usr/local/lib/python3.5/dist-packages/telegram_send.py", line 258, in configure
	    return configure()
	TypeError: configure() missing 1 required positional argument: 'conf'


How can I fix this?

**Comment by rahiel** [comment]
I suggest to again uninstall everything:
``` shell
sudo pip3 uninstall appdirs certifi colorama future python-telegram-bot telegram-send
```
And then install telegram-send only for your own user account: `pip3 install telegram-send`. Add the following line to your `~/.profile`:
``` shell
export PATH="$HOME/.local/bin:$PATH"
```
And then open a new terminal to use telegram-send.

> Configuration fails every time I hit enter after /newbot. Same output for --configure, --configure-group or --configure-channel

For this see my answer in #40, do NOT enter the `/newbot` text into telegram-send.

**Comment by rahiel** [comment]
I assume your question was answered, please open a new issue (or reopen this one) if you need further help.
