### ISSUE TITLE
Sending Videos

### ISSUE THREAD

**Issue by lightmaster** [rahiel/telegram-send#41]
How do you send a video (.mp4) and have it show up a preview of the video in Telegram?

**Comment by rahiel** [comment]
I've implemented sending videos in https://github.com/rahiel/telegram-send/commit/f8c2a6ded3ca7eca865c7e46059a2c808b884409
In the next release you can send videos with:
``` shell
telegram-send --birds.mp4 --caption "Singing Birds"
```
