### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by trickynoob** [rahiel/telegram-send#42]
Thanks for the project, everything works perfect.
Is there a possibility to start 2-3 bots on same pc ?
Can i define api in python script ?

**Comment by rahiel** [comment]
>  Is there a possibility to start 2-3 bots on same pc ?

You can use different bots by setting different config files, look at https://github.com/rahiel/telegram-send/issues/35#issuecomment-399922420 where you replace the `--configure-group` option with the configure option you need (choosing between `--configure`, `--configure-group` and `--configure-channel`).

>  Can i define api in python script ?

See the [documentation](https://www.rahielkasim.com/telegram-send/docs/api/) for the Python API.

**Comment by rahiel** [comment]
I assume your question was answered, please open a new issue (or reopen this one) if you need further help.
