### ISSUE TITLE
Animated gifs don't stay animated

### ISSUE THREAD

**Issue by lionpanthera** [rahiel/telegram-send#43]
If you post an animated gif with --image, Telegram only displays the first frame.

**Comment by rahiel** [comment]
I will add support for animated gifs in a later release.

**Comment by rahiel** [comment]
Thanks for waiting, I've implemented support for sending GIFs in https://github.com/rahiel/telegram-send/commit/ee305679a3f55012ab58ff6f2ebbadfd754f317d. In the next release you can send GIFs with:
``` shell
telegram-send --animation kitty.gif --caption "🐱"
```
