### ISSUE TITLE
Python way of sending message is not working

### ISSUE THREAD

**Issue by vchulski** [rahiel/telegram-send#46]
Dear, 

I am using your API from docker, and it's not working. 
I've followed instructions, but receiving the following error: 
![image](https://user-images.githubusercontent.com/31348740/50167870-c7446400-02f2-11e9-9717-940d679d541a.png)

While using it as a magic command: 
`!telegram-send "hello, world"`
there is no any errors and it's working fine. 

But I guess it should work from Python itself.

**Comment by rahiel** [comment]
How did you install telegram-send? Maybe you have a different telegram package that conflicts with the required `python-telegram-bot`. In your Python, do `import telegram` and post the output of `print(telegram.__author__, telegram.__version__)`

**Comment by vchulski** [comment]
Thanks for fast response. 
I've installed it with `!pip install telegram_send`
And what I've got by the code you propose: 
![image](https://user-images.githubusercontent.com/31348740/50177503-d20af300-030a-11e9-8feb-d0736b562602.png)

**Comment by vchulski** [comment]
Well, you are right. 
I've deleted it and install with pip3, but it still have some errors: 

![image](https://user-images.githubusercontent.com/31348740/50182511-2d8fad80-0318-11e9-9aa9-564d6e53aa40.png)

You are not support. So If it works usually and it's fail in my env - please let me know, and also please give a hint how it could be re-installed completely? (I mean all telegram packages)

**Comment by rahiel** [comment]
It does work usually, there is a problem in your env.

Maybe you also have a different telegram package in your env that interferes with the one that telegram-send is using, look at the output of `pip3 list`, did you install another Telegram package that is imported when you do a `import telegram`?

Best is to try installing and using it in a separate virtualenv, so you have a fresh python environment.

**Comment by vchulski** [comment]
Rahiel, it really works. 
I am sorry, issue was that python-telegram-bot was installed and one more thing is that in my case notebook should be restarted after `!pip uninstall *something* - y`. 

But I've deleted all telegram-related packages, installed it via `pip3` and all works just fine. 

Thanks for the great package!

**Comment by rahiel** [comment]
Happy it works for you! Don't forget to star this project if you enjoy it.
