### ISSUE TITLE
--configure does not working

### ISSUE THREAD

**Issue by saspol** [rahiel/telegram-send#50]
Have my working bot but telegram-send cannot use it.
Why no possible show any debug messages?
https://monosnap.com/file/xGhCwTfwED2Xawf8YKUbNSP9sTzX7a.png

**Comment by Pysis868** [comment]
Connected
Send the password

"Error! Timed Out" repeated many times.

**Comment by rahiel** [comment]
First upgrade telegram send, add `--upgrade` to the pip command you used to install telegram send, for example `sudo pip3 install telegram-send --upgrade`

Then try to configure with a longer timeout: `telegram-send --configure --timeout 60`

**Comment by rahiel** [comment]
Please try again with the suggestions above on the latest version.
