### ISSUE TITLE
Send messages to multiple groups?

### ISSUE THREAD

**Issue by Trikos** [rahiel/telegram-send#51]
Hi, it's possible to send a same message in each group where the bot was added?

**Comment by muhammadhanif** [comment]
I am waiting for the feature.

**Comment by rahiel** [comment]
HI, you need to save the telegram-send configs for the different groups, and then use them in multiple commands, also see this answer: https://github.com/rahiel/telegram-send/issues/35#issuecomment-399922420

**Comment by rahiel** [comment]
Maybe I can add a feature to make this easier.

**Comment by rahiel** [comment]
> Hi, it's possible to send a same message in each group where the bot was added?

@Trikos @muhammadhanif It is possible following these instructions: https://github.com/rahiel/telegram-send#how-to-send-the-same-message-to-multiple-users

Make sure that you first update to the latest version of telegram-send

**Comment by muhammadhanif** [comment]
Thank you @rahiel
