### ISSUE TITLE
<!DOCTYPE …> HTML Tag

### ISSUE THREAD

**Issue by joesixpack** [rahiel/telegram-send#53]
HTML 5 compatibiliy appears to be lacking when parsing HTML.

https://html.com/tags/doctype/

![image](https://user-images.githubusercontent.com/23145642/61801067-0388f700-ade3-11e9-80bd-b70186136c62.png)

**Comment by rahiel** [comment]
Not all HTML tags are supported, see the formatting options to see which HTML tags are supported by Telegram: https://core.telegram.org/bots/api#formatting-options
