### ISSUE TITLE
Send stickers

### ISSUE THREAD

**Issue by vaishnavm217** [rahiel/telegram-send#54]
Anyway to send telegram stickers?

**Comment by vaishnavm217** [comment]
Hi I have already made a PR for this issue, I might be deleting it and making new one as It would get added in Hacktober fest :) It would be great if you could look through the commit and suggest any changes it required

**Comment by rahiel** [comment]
Hey @vaishnavm217, you're free to close the PR and make a new one for Hacktoberfest :smile:. I left a review at #55, if you address those few comments and base the PR on the current master, I will merge it.

Thanks for your work!

**Comment by rahiel** [comment]
Resolved in #58
