### ISSUE TITLE
ModuleNotFoundError: No module named 'version'

### ISSUE THREAD

**Issue by derlin** [rahiel/telegram-send#56]
Hi there, and first thank you for this great tool.

When trying to either import or run `telegram-send` from the terminal, it cannot find the module `version` (is it the `telegram-cli.version` module that should be imported here ?):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.7/site-packages/telegram_send.py", line 34, in <module>
    from version import __version__
ModuleNotFoundError: No module named 'version'
```

*Installation* through pip (inside a python 3 virtualenv) using:

    pip install telegram-send

*OS/version*:

* Ubuntu 18.04/python 3.6
* MacOS Mojave/python 3.7

**Comment by victordek** [comment]
Same issue.

Version for python2 works, though.

**Comment by rahiel** [comment]
I apologize for the inconvenience, I made a mistake in the last release.

I've released a new version that should fix this. Please update:
``` shell
pip install telegram-send --upgrade
```
