### ISSUE TITLE
Connection timeout even with enormous --timeout argument

### ISSUE THREAD

**Issue by drthanwho** [rahiel/telegram-send#64]
Been trying to use telegram-send to send videos from a directory, however it will not work for larger files no matter how much I increase the arguments. 

I was able to send 1MB and 5MB videos (had to add timeout for the 5MB). But when trying to send a 13MB video command errors out. I have even added something like 
`--timeout 99999999999999999999999999999999999 `
and still won't work. It keeps saying to increase it further?

The limit is 50MB so I'm not sure why this is happening

**Comment by meliksahd** [comment]
I committed a fix for this issue and it is pending in pull requests right now. You can pull your version from there

**Comment by drthanwho** [comment]
I'm not sure how? I've never done anything like that. Any pointer would be greatly appreciated 

Also strange this was fixed so many months ago but still hasn't been pulled into master?

**Comment by meliksahd** [comment]
you can just find telegram_send.py in your pc and apply these changes manually.

https://github.com/rahiel/telegram-send/pull/60/files

I guess rahiel has been away for a very long time now. He is not likely to pull any commits.

**Comment by drthanwho** [comment]
Ah that's what I thought of doing. Just couldn't find where the fille got installed. Good to know I was heading down the right way haha

> I guess rahiel has been away for a very long time now.

There was a pull 25 days ago  😂

**Comment by a-nice-username** [comment]
@meliksahd thanks for the patch, the owner of this repo should gave merged that

**Comment by rahiel** [comment]
This bug is fixed in version 0.30 now, thanks for waiting everyone 😅
