### ISSUE TITLE
send emoji unicode

### ISSUE THREAD

**Issue by Martina78** [rahiel/telegram-send#70]
is it possible to send emoji by unicode or other method?
fetching string manually without use "telegram-send", for example, you can insert unicode text and send emoji.
For example: %E2%9D%A4 is heart

this is unicode site i retrieve code infos:
https://apps.timwhitlock.info/emoji/tables/unicode

thanks

**Comment by rahiel** [comment]
You can copy emoji from the first "Native" column in that emoji table and send it:
```
telegram-send '😍'
```

Simply input them directly
