### ISSUE TITLE
No module named 'telegram.constants'; 'telegram' is not a package

### ISSUE THREAD

**Issue by shepelevstas** [rahiel/telegram-send#73]
Installed in local /env folder, created .conf file manually, trying to send a message from a Django view function.

**Comment by arch88** [comment]
I have the same problem. The only workaround I found was to rename my script file to main.py

**Comment by rahiel** [comment]
1. Make sure your own python script is not named `telegram.py` as that causes a conflict with the telegram bot API library that we use.
2. You might have a conflict with a different module that is also using the `telegram` name, this package depends on the https://github.com/python-telegram-bot/python-telegram-bot library that ships with the `telegram.constants` module. Try again in a fresh virtualenv.
