### ISSUE TITLE
Send messages in Group or Channel - I'm getting working only on Chat

### ISSUE THREAD

**Issue by eugjr** [rahiel/telegram-send#78]
Hi, I've able to set up the telegram-send on a Amazon Lightsail instance, sending messages from a python script.
I"ve been able to set up correctly the bot, and it responds within the 1x1 chat, but when I've added the bot to a group or a channel, it doesnt send anything (setted it as admin and enabled ass permissions).

Tried to create a channel config, but as I dont have sudo acess trought SFTP, I cant acess and edit the location of the config files.

**Comment by rahiel** [comment]
You need a different config for each different chat. You can specify the location of the config file with the `conf` option, see for example this: https://github.com/rahiel/telegram-send#how-to-send-the-same-message-to-multiple-users

You can put the config files wherever you do have access.
