### ISSUE TITLE
Messaging specific users

### ISSUE THREAD

**Issue by nicolo-tellini** [rahiel/telegram-send#82]
Hello,

really appreciated an useful tools. 
I was wondering if the command telegram-send can send messages to specific user by, for example, taking as input the @username ? Or accomplishing this task in some way, without send the message to all the people inside the same group or channel.  

Best regards,

Nicolò Tellini

**Comment by rahiel** [comment]
Then you need to setup telegram-send separately for each user in a different config file (by using a different `--conf user1.conf` etc. for each user) and then you can send a message to all users with one command by combining all config files:
```
telegram-send "HELLOOOOO" --config user1.conf user2.conf user3.conf
```

**Comment by rahiel** [comment]
Also see this section in the readme: https://github.com/rahiel/telegram-send#how-to-send-the-same-message-to-multiple-users
