### ISSUE TITLE
Python 2 not supported - SyntaxError: invalid syntax while configuring

### ISSUE THREAD

**Issue by semarngaji** [rahiel/telegram-send#88]
Trying to configure and got this
I am using Raspbian/RaspberryPi
Help me please

myname@mymachine:/ $ sudo telegram-send --configure
Traceback (most recent call last):
  File "/usr/local/bin/telegram-send", line 7, in <module>
    from telegram_send import main
  File "/usr/local/lib/python2.7/dist-packages/telegram_send.py", line 28, in <module>
    import telegram
  File "/usr/local/lib/python2.7/dist-packages/telegram/__init__.py", line 21, in <module>
    from .base import TelegramObject
  File "/usr/local/lib/python2.7/dist-packages/telegram/base.py", line 42
    _id_attrs: Tuple[Any, ...] = ()
             ^
SyntaxError: invalid syntax

**Comment by baddymaster** [comment]
+1

**Comment by oddmean** [comment]
@semarngaji as you can see in the traceback, the `telegram` package is a python**2** one, while `telegram-send` is written in python**3** (which is not backwards-compatible with python2) and expects python3 `telegram` module, which may be obtained by running `pip3 install telegram`

**Comment by baddymaster** [comment]
@oddmean Is `telegram-send` compatible with Python 3.5? I see this same error when I invoke `telegram-send` from Python 3.5, but works fine with Python 3.8.

**Comment by oddmean** [comment]
@baddymaster I'm not sure about Python 3.5, can't find exact version requirements.

**Comment by rahiel** [comment]
We don't support Python 2, we need at minimum Python 3.6 now, please install the latest version.

> @semarngaji as you can see in the traceback, the `telegram` package is a python**2** one, while `telegram-send` is written in python**3** (which is not backwards-compatible with python2) and expects python3 `telegram` module, which may be obtained by running `pip3 install telegram`

Telegram-send will break with if you install that telegram module, it uses https://github.com/python-telegram-bot/python-telegram-bot instead and it will automatically install it if you just install telegram-send
