### ISSUE TITLE
Faced a weird error today 

### ISSUE THREAD

**Issue by Divyanshu-Modi** [rahiel/telegram-send#99]
Traceback (most recent call last):
  File "/home/divyanshu/.local/bin/telegram-send", line 5, in <module>
    from telegram_send.telegram_send import main
ModuleNotFoundError: No module named 'telegram_send.telegram_send'; 'telegram_send' is not a package

**Comment by chrischma** [comment]
interesting! same here! appeared just today!

**Comment by chrischma** [comment]
just downgraded to version 0.25 with: 
`pip install telegram-send==0.25`

everything works fine again. possible the new release is just broken...

**Comment by Llewellynvdm** [comment]
Same here, also received this error.

**Comment by Divyanshu-Modi** [comment]
It's fixed now
For me temp fix was to use this cmd

**Comment by rahiel** [comment]
I just released version 0.29 that should fix this for everyone, I was having some troubles with python packaging.

**Comment by Divyanshu-Modi** [comment]
> I just released version 0.29 that should fix this for everyone, I was having some troubles with python packaging.
> 
> Fixed in: [ee38532](https://github.com/rahiel/telegram-send/commit/ee385323c559494c2b2a2f194e1e5af75a4a4f36)

nice : )
